development:
  adapter: mysql
  database: mychores_development
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock
  
test:
  adapter: mysql
  database: mychores_test
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql
  database: mychores_production
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock